// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: trust_anchor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrustAnchor_Write_FullMethodName          = "/trust_anchor.TrustAnchor/write"
	TrustAnchor_Read_FullMethodName           = "/trust_anchor.TrustAnchor/read"
	TrustAnchor_AddOwner_FullMethodName       = "/trust_anchor.TrustAnchor/add_owner"
	TrustAnchor_UpdateTrustVec_FullMethodName = "/trust_anchor.TrustAnchor/update_trust_vec"
	TrustAnchor_SetConfig_FullMethodName      = "/trust_anchor.TrustAnchor/set_config"
	TrustAnchor_GetMap_FullMethodName         = "/trust_anchor.TrustAnchor/get_map"
	TrustAnchor_GetCategory_FullMethodName    = "/trust_anchor.TrustAnchor/get_category"
	TrustAnchor_GetHistory_FullMethodName     = "/trust_anchor.TrustAnchor/get_history"
	TrustAnchor_GetOtherIds_FullMethodName    = "/trust_anchor.TrustAnchor/get_other_ids"
)

// TrustAnchorClient is the client API for TrustAnchor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC services. First, call add_owner to receive a client ID (uint64). After that, all gRPC requests should include the client id as binary metadata in big-endian in the field 'id-bin'.
// There is no authentication in this implementation, you can in fact switch clients by using their ID.
// Data categories are currently identified by a single byte.
type TrustAnchorClient interface {
	// write to a category kv-space you have access to
	Write(ctx context.Context, in *Write, opts ...grpc.CallOption) (*Empty, error)
	// read from a category kv-space
	Read(ctx context.Context, in *Read, opts ...grpc.CallOption) (*ReadResponse, error)
	// register new client and receive a client ID
	AddOwner(ctx context.Context, in *AddOwner, opts ...grpc.CallOption) (*AddOwnerResponse, error)
	// submit vector of deltas to the trust vector you have for another client. if this is the first call, the trust vector starts with all zeros
	UpdateTrustVec(ctx context.Context, in *UpdateTrustVec, opts ...grpc.CallOption) (*Empty, error)
	// submit configurations for data categories. If the scalar product of your trust vector towards another client and a category's config vector is higher than a threshold (currently hardcoded, 40), that client has access to your category
	SetConfig(ctx context.Context, in *SetConfig, opts ...grpc.CallOption) (*Empty, error)
	// request general information on your data categories, peer clients and their access to your categories
	GetMap(ctx context.Context, in *GetMap, opts ...grpc.CallOption) (*GetMapResponse, error)
	// request all kv-pairs from a data category
	GetCategory(ctx context.Context, in *GetCategory, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	// get audit log information for a specific kv-pair
	GetHistory(ctx context.Context, in *GetHistory, opts ...grpc.CallOption) (*History, error)
	// get the current set of all client IDs
	GetOtherIds(ctx context.Context, in *GetOtherIds, opts ...grpc.CallOption) (*GetOtherIdsResponse, error)
}

type trustAnchorClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustAnchorClient(cc grpc.ClientConnInterface) TrustAnchorClient {
	return &trustAnchorClient{cc}
}

func (c *trustAnchorClient) Write(ctx context.Context, in *Write, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TrustAnchor_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) Read(ctx context.Context, in *Read, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, TrustAnchor_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) AddOwner(ctx context.Context, in *AddOwner, opts ...grpc.CallOption) (*AddOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOwnerResponse)
	err := c.cc.Invoke(ctx, TrustAnchor_AddOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) UpdateTrustVec(ctx context.Context, in *UpdateTrustVec, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TrustAnchor_UpdateTrustVec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) SetConfig(ctx context.Context, in *SetConfig, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, TrustAnchor_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) GetMap(ctx context.Context, in *GetMap, opts ...grpc.CallOption) (*GetMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMapResponse)
	err := c.cc.Invoke(ctx, TrustAnchor_GetMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) GetCategory(ctx context.Context, in *GetCategory, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, TrustAnchor_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) GetHistory(ctx context.Context, in *GetHistory, opts ...grpc.CallOption) (*History, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(History)
	err := c.cc.Invoke(ctx, TrustAnchor_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustAnchorClient) GetOtherIds(ctx context.Context, in *GetOtherIds, opts ...grpc.CallOption) (*GetOtherIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOtherIdsResponse)
	err := c.cc.Invoke(ctx, TrustAnchor_GetOtherIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustAnchorServer is the server API for TrustAnchor service.
// All implementations must embed UnimplementedTrustAnchorServer
// for forward compatibility.
//
// gRPC services. First, call add_owner to receive a client ID (uint64). After that, all gRPC requests should include the client id as binary metadata in big-endian in the field 'id-bin'.
// There is no authentication in this implementation, you can in fact switch clients by using their ID.
// Data categories are currently identified by a single byte.
type TrustAnchorServer interface {
	// write to a category kv-space you have access to
	Write(context.Context, *Write) (*Empty, error)
	// read from a category kv-space
	Read(context.Context, *Read) (*ReadResponse, error)
	// register new client and receive a client ID
	AddOwner(context.Context, *AddOwner) (*AddOwnerResponse, error)
	// submit vector of deltas to the trust vector you have for another client. if this is the first call, the trust vector starts with all zeros
	UpdateTrustVec(context.Context, *UpdateTrustVec) (*Empty, error)
	// submit configurations for data categories. If the scalar product of your trust vector towards another client and a category's config vector is higher than a threshold (currently hardcoded, 40), that client has access to your category
	SetConfig(context.Context, *SetConfig) (*Empty, error)
	// request general information on your data categories, peer clients and their access to your categories
	GetMap(context.Context, *GetMap) (*GetMapResponse, error)
	// request all kv-pairs from a data category
	GetCategory(context.Context, *GetCategory) (*GetCategoryResponse, error)
	// get audit log information for a specific kv-pair
	GetHistory(context.Context, *GetHistory) (*History, error)
	// get the current set of all client IDs
	GetOtherIds(context.Context, *GetOtherIds) (*GetOtherIdsResponse, error)
	mustEmbedUnimplementedTrustAnchorServer()
}

// UnimplementedTrustAnchorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrustAnchorServer struct{}

func (UnimplementedTrustAnchorServer) Write(context.Context, *Write) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedTrustAnchorServer) Read(context.Context, *Read) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedTrustAnchorServer) AddOwner(context.Context, *AddOwner) (*AddOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOwner not implemented")
}
func (UnimplementedTrustAnchorServer) UpdateTrustVec(context.Context, *UpdateTrustVec) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrustVec not implemented")
}
func (UnimplementedTrustAnchorServer) SetConfig(context.Context, *SetConfig) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedTrustAnchorServer) GetMap(context.Context, *GetMap) (*GetMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMap not implemented")
}
func (UnimplementedTrustAnchorServer) GetCategory(context.Context, *GetCategory) (*GetCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedTrustAnchorServer) GetHistory(context.Context, *GetHistory) (*History, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedTrustAnchorServer) GetOtherIds(context.Context, *GetOtherIds) (*GetOtherIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOtherIds not implemented")
}
func (UnimplementedTrustAnchorServer) mustEmbedUnimplementedTrustAnchorServer() {}
func (UnimplementedTrustAnchorServer) testEmbeddedByValue()                     {}

// UnsafeTrustAnchorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrustAnchorServer will
// result in compilation errors.
type UnsafeTrustAnchorServer interface {
	mustEmbedUnimplementedTrustAnchorServer()
}

func RegisterTrustAnchorServer(s grpc.ServiceRegistrar, srv TrustAnchorServer) {
	// If the following call panics, it indicates UnimplementedTrustAnchorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrustAnchor_ServiceDesc, srv)
}

func _TrustAnchor_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Write)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).Write(ctx, req.(*Write))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Read)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).Read(ctx, req.(*Read))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_AddOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).AddOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_AddOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).AddOwner(ctx, req.(*AddOwner))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_UpdateTrustVec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrustVec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).UpdateTrustVec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_UpdateTrustVec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).UpdateTrustVec(ctx, req.(*UpdateTrustVec))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).SetConfig(ctx, req.(*SetConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_GetMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).GetMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_GetMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).GetMap(ctx, req.(*GetMap))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).GetCategory(ctx, req.(*GetCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).GetHistory(ctx, req.(*GetHistory))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustAnchor_GetOtherIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtherIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustAnchorServer).GetOtherIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TrustAnchor_GetOtherIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustAnchorServer).GetOtherIds(ctx, req.(*GetOtherIds))
	}
	return interceptor(ctx, in, info, handler)
}

// TrustAnchor_ServiceDesc is the grpc.ServiceDesc for TrustAnchor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrustAnchor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trust_anchor.TrustAnchor",
	HandlerType: (*TrustAnchorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "write",
			Handler:    _TrustAnchor_Write_Handler,
		},
		{
			MethodName: "read",
			Handler:    _TrustAnchor_Read_Handler,
		},
		{
			MethodName: "add_owner",
			Handler:    _TrustAnchor_AddOwner_Handler,
		},
		{
			MethodName: "update_trust_vec",
			Handler:    _TrustAnchor_UpdateTrustVec_Handler,
		},
		{
			MethodName: "set_config",
			Handler:    _TrustAnchor_SetConfig_Handler,
		},
		{
			MethodName: "get_map",
			Handler:    _TrustAnchor_GetMap_Handler,
		},
		{
			MethodName: "get_category",
			Handler:    _TrustAnchor_GetCategory_Handler,
		},
		{
			MethodName: "get_history",
			Handler:    _TrustAnchor_GetHistory_Handler,
		},
		{
			MethodName: "get_other_ids",
			Handler:    _TrustAnchor_GetOtherIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trust_anchor.proto",
}
