// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trust_anchor.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// try to identify source of error
type Status int32

const (
	Status_Ok Status = 0
	// client side issues
	Status_BadRequest Status = 1
	// server side issues
	Status_InternalError Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Ok",
		1: "BadRequest",
		2: "InternalError",
	}
	Status_value = map[string]int32{
		"Ok":            0,
		"BadRequest":    1,
		"InternalError": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_trust_anchor_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_trust_anchor_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{0}
}

// Request Type for DenKrement Calls to topic: TA/Procedures
type TrustAnchorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*TrustAnchorRequest_Write
	//	*TrustAnchorRequest_Read
	//	*TrustAnchorRequest_UpdateTrustVec
	//	*TrustAnchorRequest_AddOwner
	//	*TrustAnchorRequest_SetConfig
	//	*TrustAnchorRequest_GetMap
	//	*TrustAnchorRequest_GetCategory
	//	*TrustAnchorRequest_GetHistory
	//	*TrustAnchorRequest_GetOtherIds
	Request       isTrustAnchorRequest_Request `protobuf_oneof:"request"`
	SenderId      uint64                       `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustAnchorRequest) Reset() {
	*x = TrustAnchorRequest{}
	mi := &file_trust_anchor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAnchorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAnchorRequest) ProtoMessage() {}

func (x *TrustAnchorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAnchorRequest.ProtoReflect.Descriptor instead.
func (*TrustAnchorRequest) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{0}
}

func (x *TrustAnchorRequest) GetRequest() isTrustAnchorRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TrustAnchorRequest) GetWrite() *Write {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetRead() *Read {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetUpdateTrustVec() *UpdateTrustVec {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_UpdateTrustVec); ok {
			return x.UpdateTrustVec
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetAddOwner() *AddOwner {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_AddOwner); ok {
			return x.AddOwner
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetSetConfig() *SetConfig {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_SetConfig); ok {
			return x.SetConfig
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetGetMap() *GetMap {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_GetMap); ok {
			return x.GetMap
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetGetCategory() *GetCategory {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_GetCategory); ok {
			return x.GetCategory
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetGetHistory() *GetHistory {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_GetHistory); ok {
			return x.GetHistory
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetGetOtherIds() *GetOtherIds {
	if x != nil {
		if x, ok := x.Request.(*TrustAnchorRequest_GetOtherIds); ok {
			return x.GetOtherIds
		}
	}
	return nil
}

func (x *TrustAnchorRequest) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type isTrustAnchorRequest_Request interface {
	isTrustAnchorRequest_Request()
}

type TrustAnchorRequest_Write struct {
	Write *Write `protobuf:"bytes,2,opt,name=write,proto3,oneof"`
}

type TrustAnchorRequest_Read struct {
	Read *Read `protobuf:"bytes,3,opt,name=read,proto3,oneof"`
}

type TrustAnchorRequest_UpdateTrustVec struct {
	UpdateTrustVec *UpdateTrustVec `protobuf:"bytes,4,opt,name=update_trust_vec,json=updateTrustVec,proto3,oneof"`
}

type TrustAnchorRequest_AddOwner struct {
	AddOwner *AddOwner `protobuf:"bytes,5,opt,name=add_owner,json=addOwner,proto3,oneof"`
}

type TrustAnchorRequest_SetConfig struct {
	SetConfig *SetConfig `protobuf:"bytes,6,opt,name=set_config,json=setConfig,proto3,oneof"`
}

type TrustAnchorRequest_GetMap struct {
	GetMap *GetMap `protobuf:"bytes,7,opt,name=get_map,json=getMap,proto3,oneof"`
}

type TrustAnchorRequest_GetCategory struct {
	GetCategory *GetCategory `protobuf:"bytes,8,opt,name=get_category,json=getCategory,proto3,oneof"`
}

type TrustAnchorRequest_GetHistory struct {
	GetHistory *GetHistory `protobuf:"bytes,9,opt,name=get_history,json=getHistory,proto3,oneof"`
}

type TrustAnchorRequest_GetOtherIds struct {
	GetOtherIds *GetOtherIds `protobuf:"bytes,10,opt,name=get_other_ids,json=getOtherIds,proto3,oneof"`
}

func (*TrustAnchorRequest_Write) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_Read) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_UpdateTrustVec) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_AddOwner) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_SetConfig) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_GetMap) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_GetCategory) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_GetHistory) isTrustAnchorRequest_Request() {}

func (*TrustAnchorRequest_GetOtherIds) isTrustAnchorRequest_Request() {}

// Response Type for DenKrement Calls to topic: TA/Procedures
type TrustAnchorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TrustAnchorResponse_EmptyResponse
	//	*TrustAnchorResponse_ReadResponse
	//	*TrustAnchorResponse_AddOwnerResponse
	//	*TrustAnchorResponse_GetMapResponse
	//	*TrustAnchorResponse_GetCategoryResponse
	//	*TrustAnchorResponse_GetHistoryResponse
	//	*TrustAnchorResponse_GetOtherIdsResponse
	Response        isTrustAnchorResponse_Response `protobuf_oneof:"response"`
	Status          Status                         `protobuf:"varint,1,opt,name=status,proto3,enum=trust_anchor.Status" json:"status,omitempty"`
	ExecutionTimeUs uint32                         `protobuf:"varint,2,opt,name=execution_time_us,json=executionTimeUs,proto3" json:"execution_time_us,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrustAnchorResponse) Reset() {
	*x = TrustAnchorResponse{}
	mi := &file_trust_anchor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAnchorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAnchorResponse) ProtoMessage() {}

func (x *TrustAnchorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAnchorResponse.ProtoReflect.Descriptor instead.
func (*TrustAnchorResponse) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{1}
}

func (x *TrustAnchorResponse) GetResponse() isTrustAnchorResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TrustAnchorResponse) GetEmptyResponse() *Empty {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_EmptyResponse); ok {
			return x.EmptyResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetReadResponse() *ReadResponse {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_ReadResponse); ok {
			return x.ReadResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetAddOwnerResponse() *AddOwnerResponse {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_AddOwnerResponse); ok {
			return x.AddOwnerResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetGetMapResponse() *GetMapResponse {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_GetMapResponse); ok {
			return x.GetMapResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetGetCategoryResponse() *GetCategoryResponse {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_GetCategoryResponse); ok {
			return x.GetCategoryResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetGetHistoryResponse() *History {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_GetHistoryResponse); ok {
			return x.GetHistoryResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetGetOtherIdsResponse() *GetOtherIdsResponse {
	if x != nil {
		if x, ok := x.Response.(*TrustAnchorResponse_GetOtherIdsResponse); ok {
			return x.GetOtherIdsResponse
		}
	}
	return nil
}

func (x *TrustAnchorResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Ok
}

func (x *TrustAnchorResponse) GetExecutionTimeUs() uint32 {
	if x != nil {
		return x.ExecutionTimeUs
	}
	return 0
}

type isTrustAnchorResponse_Response interface {
	isTrustAnchorResponse_Response()
}

type TrustAnchorResponse_EmptyResponse struct {
	EmptyResponse *Empty `protobuf:"bytes,3,opt,name=empty_response,json=emptyResponse,proto3,oneof"`
}

type TrustAnchorResponse_ReadResponse struct {
	ReadResponse *ReadResponse `protobuf:"bytes,4,opt,name=read_response,json=readResponse,proto3,oneof"`
}

type TrustAnchorResponse_AddOwnerResponse struct {
	AddOwnerResponse *AddOwnerResponse `protobuf:"bytes,5,opt,name=add_owner_response,json=addOwnerResponse,proto3,oneof"`
}

type TrustAnchorResponse_GetMapResponse struct {
	GetMapResponse *GetMapResponse `protobuf:"bytes,6,opt,name=get_map_response,json=getMapResponse,proto3,oneof"`
}

type TrustAnchorResponse_GetCategoryResponse struct {
	GetCategoryResponse *GetCategoryResponse `protobuf:"bytes,7,opt,name=get_category_response,json=getCategoryResponse,proto3,oneof"`
}

type TrustAnchorResponse_GetHistoryResponse struct {
	GetHistoryResponse *History `protobuf:"bytes,8,opt,name=get_history_response,json=getHistoryResponse,proto3,oneof"`
}

type TrustAnchorResponse_GetOtherIdsResponse struct {
	GetOtherIdsResponse *GetOtherIdsResponse `protobuf:"bytes,9,opt,name=get_other_ids_response,json=getOtherIdsResponse,proto3,oneof"`
}

func (*TrustAnchorResponse_EmptyResponse) isTrustAnchorResponse_Response() {}

func (*TrustAnchorResponse_ReadResponse) isTrustAnchorResponse_Response() {}

func (*TrustAnchorResponse_AddOwnerResponse) isTrustAnchorResponse_Response() {}

func (*TrustAnchorResponse_GetMapResponse) isTrustAnchorResponse_Response() {}

func (*TrustAnchorResponse_GetCategoryResponse) isTrustAnchorResponse_Response() {}

func (*TrustAnchorResponse_GetHistoryResponse) isTrustAnchorResponse_Response() {}

func (*TrustAnchorResponse_GetOtherIdsResponse) isTrustAnchorResponse_Response() {}

// little helper
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_trust_anchor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{2}
}

// newly created ID of a new client, should b included in gRPC metadata for other requests
type AddOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       uint64                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOwnerResponse) Reset() {
	*x = AddOwnerResponse{}
	mi := &file_trust_anchor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOwnerResponse) ProtoMessage() {}

func (x *AddOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOwnerResponse.ProtoReflect.Descriptor instead.
func (*AddOwnerResponse) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{3}
}

func (x *AddOwnerResponse) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

type Write struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_trust_anchor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{4}
}

func (x *Write) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Write) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Read struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Location *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// include 'inclusion proof' from audit log for current version of that kv entry in response
	IncludeProof  bool `protobuf:"varint,2,opt,name=include_proof,json=includeProof,proto3" json:"include_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_trust_anchor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{5}
}

func (x *Read) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Read) GetIncludeProof() bool {
	if x != nil {
		return x.IncludeProof
	}
	return false
}

type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload data
	Value         []byte      `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Proof         *ProofEntry `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_trust_anchor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{6}
}

func (x *ReadResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReadResponse) GetProof() *ProofEntry {
	if x != nil {
		return x.Proof
	}
	return nil
}

type ProofEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// leaf hash of corresponding entry in Audit Log
	LeafHash []byte `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	// leaf index of corresponding entry in Audit Log
	LeafIndex int64 `protobuf:"varint,2,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	// the log root at the size of the request time
	LogRoot []byte `protobuf:"bytes,3,opt,name=log_root,json=logRoot,proto3" json:"log_root,omitempty"`
	// the size of the tree at request time
	LogSize int64 `protobuf:"varint,4,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`
	// node hashes from Merkle tree required for inclusion proof
	InclusionProof [][]byte `protobuf:"bytes,5,rep,name=inclusion_proof,json=inclusionProof,proto3" json:"inclusion_proof,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProofEntry) Reset() {
	*x = ProofEntry{}
	mi := &file_trust_anchor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofEntry) ProtoMessage() {}

func (x *ProofEntry) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofEntry.ProtoReflect.Descriptor instead.
func (*ProofEntry) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{7}
}

func (x *ProofEntry) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

func (x *ProofEntry) GetLeafIndex() int64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *ProofEntry) GetLogRoot() []byte {
	if x != nil {
		return x.LogRoot
	}
	return nil
}

func (x *ProofEntry) GetLogSize() int64 {
	if x != nil {
		return x.LogSize
	}
	return 0
}

func (x *ProofEntry) GetInclusionProof() [][]byte {
	if x != nil {
		return x.InclusionProof
	}
	return nil
}

type Location struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OwnerId uint64                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// use the first byte only
	Category      []byte `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Key           []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_trust_anchor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{8}
}

func (x *Location) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Location) GetCategory() []byte {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Location) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type UpdateTrustVec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OidTrustee    uint64                 `protobuf:"varint,1,opt,name=oid_trustee,json=oidTrustee,proto3" json:"oid_trustee,omitempty"`
	TrustDelta    []int32                `protobuf:"varint,2,rep,packed,name=trust_delta,json=trustDelta,proto3" json:"trust_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrustVec) Reset() {
	*x = UpdateTrustVec{}
	mi := &file_trust_anchor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrustVec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrustVec) ProtoMessage() {}

func (x *UpdateTrustVec) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrustVec.ProtoReflect.Descriptor instead.
func (*UpdateTrustVec) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTrustVec) GetOidTrustee() uint64 {
	if x != nil {
		return x.OidTrustee
	}
	return 0
}

func (x *UpdateTrustVec) GetTrustDelta() []int32 {
	if x != nil {
		return x.TrustDelta
	}
	return nil
}

type AddOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOwner) Reset() {
	*x = AddOwner{}
	mi := &file_trust_anchor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOwner) ProtoMessage() {}

func (x *AddOwner) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOwner.ProtoReflect.Descriptor instead.
func (*AddOwner) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{10}
}

type SetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*SetConfig_CatConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfig) Reset() {
	*x = SetConfig{}
	mi := &file_trust_anchor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfig) ProtoMessage() {}

func (x *SetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfig.ProtoReflect.Descriptor instead.
func (*SetConfig) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{11}
}

func (x *SetConfig) GetConfigs() []*SetConfig_CatConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type CortexData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafHash      []byte                 `protobuf:"bytes,1,opt,name=leaf_hash,json=leafHash,proto3" json:"leaf_hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CortexData) Reset() {
	*x = CortexData{}
	mi := &file_trust_anchor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CortexData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CortexData) ProtoMessage() {}

func (x *CortexData) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CortexData.ProtoReflect.Descriptor instead.
func (*CortexData) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{12}
}

func (x *CortexData) GetLeafHash() []byte {
	if x != nil {
		return x.LeafHash
	}
	return nil
}

func (x *CortexData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	DataHash      []byte                 `protobuf:"bytes,2,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	PrevLeafHash  []byte                 `protobuf:"bytes,3,opt,name=prev_leaf_hash,json=prevLeafHash,proto3" json:"prev_leaf_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_trust_anchor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{13}
}

func (x *AuditLogEntry) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *AuditLogEntry) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

func (x *AuditLogEntry) GetPrevLeafHash() []byte {
	if x != nil {
		return x.PrevLeafHash
	}
	return nil
}

type GetMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMap) Reset() {
	*x = GetMap{}
	mi := &file_trust_anchor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMap) ProtoMessage() {}

func (x *GetMap) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMap.ProtoReflect.Descriptor instead.
func (*GetMap) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{14}
}

type GetMapResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	OwnCategories []*GetMapResponse_Origin `protobuf:"bytes,1,rep,name=own_categories,json=ownCategories,proto3" json:"own_categories,omitempty"`
	Links         []*GetMapResponse_Link   `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	Peers         []*GetMapResponse_Peer   `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse) Reset() {
	*x = GetMapResponse{}
	mi := &file_trust_anchor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse) ProtoMessage() {}

func (x *GetMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse.ProtoReflect.Descriptor instead.
func (*GetMapResponse) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{15}
}

func (x *GetMapResponse) GetOwnCategories() []*GetMapResponse_Origin {
	if x != nil {
		return x.OwnCategories
	}
	return nil
}

func (x *GetMapResponse) GetLinks() []*GetMapResponse_Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GetMapResponse) GetPeers() []*GetMapResponse_Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       uint64                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Category      []byte                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategory) Reset() {
	*x = GetCategory{}
	mi := &file_trust_anchor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategory) ProtoMessage() {}

func (x *GetCategory) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategory.ProtoReflect.Descriptor instead.
func (*GetCategory) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{16}
}

func (x *GetCategory) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetCategory) GetCategory() []byte {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Entries       []*GetCategoryResponse_KvPair `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse) Reset() {
	*x = GetCategoryResponse{}
	mi := &file_trust_anchor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse) ProtoMessage() {}

func (x *GetCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{17}
}

func (x *GetCategoryResponse) GetEntries() []*GetCategoryResponse_KvPair {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistory) Reset() {
	*x = GetHistory{}
	mi := &file_trust_anchor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistory) ProtoMessage() {}

func (x *GetHistory) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistory.ProtoReflect.Descriptor instead.
func (*GetHistory) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{18}
}

func (x *GetHistory) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type History struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	History       []*History_HistoryEntry `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *History) Reset() {
	*x = History{}
	mi := &file_trust_anchor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{19}
}

func (x *History) GetHistory() []*History_HistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

type GetOtherIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOtherIds) Reset() {
	*x = GetOtherIds{}
	mi := &file_trust_anchor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOtherIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOtherIds) ProtoMessage() {}

func (x *GetOtherIds) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOtherIds.ProtoReflect.Descriptor instead.
func (*GetOtherIds) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{20}
}

type GetOtherIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtherIds      []uint64               `protobuf:"varint,1,rep,packed,name=other_ids,json=otherIds,proto3" json:"other_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOtherIdsResponse) Reset() {
	*x = GetOtherIdsResponse{}
	mi := &file_trust_anchor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOtherIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOtherIdsResponse) ProtoMessage() {}

func (x *GetOtherIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOtherIdsResponse.ProtoReflect.Descriptor instead.
func (*GetOtherIdsResponse) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{21}
}

func (x *GetOtherIdsResponse) GetOtherIds() []uint64 {
	if x != nil {
		return x.OtherIds
	}
	return nil
}

type SetConfig_CatConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// use the first byte only
	Category         []byte `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	DecisionFunction []byte `protobuf:"bytes,2,opt,name=decision_function,json=decisionFunction,proto3" json:"decision_function,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetConfig_CatConfig) Reset() {
	*x = SetConfig_CatConfig{}
	mi := &file_trust_anchor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfig_CatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfig_CatConfig) ProtoMessage() {}

func (x *SetConfig_CatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfig_CatConfig.ProtoReflect.Descriptor instead.
func (*SetConfig_CatConfig) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{11, 0}
}

func (x *SetConfig_CatConfig) GetCategory() []byte {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *SetConfig_CatConfig) GetDecisionFunction() []byte {
	if x != nil {
		return x.DecisionFunction
	}
	return nil
}

type GetMapResponse_Origin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    []byte                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Trustees      []uint64               `protobuf:"varint,2,rep,packed,name=trustees,proto3" json:"trustees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse_Origin) Reset() {
	*x = GetMapResponse_Origin{}
	mi := &file_trust_anchor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse_Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse_Origin) ProtoMessage() {}

func (x *GetMapResponse_Origin) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse_Origin.ProtoReflect.Descriptor instead.
func (*GetMapResponse_Origin) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{15, 0}
}

func (x *GetMapResponse_Origin) GetCategoryId() []byte {
	if x != nil {
		return x.CategoryId
	}
	return nil
}

func (x *GetMapResponse_Origin) GetTrustees() []uint64 {
	if x != nil {
		return x.Trustees
	}
	return nil
}

type GetMapResponse_Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       uint64                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Categories    []byte                 `protobuf:"bytes,2,opt,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse_Link) Reset() {
	*x = GetMapResponse_Link{}
	mi := &file_trust_anchor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse_Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse_Link) ProtoMessage() {}

func (x *GetMapResponse_Link) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse_Link.ProtoReflect.Descriptor instead.
func (*GetMapResponse_Link) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{15, 1}
}

func (x *GetMapResponse_Link) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetMapResponse_Link) GetCategories() []byte {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetMapResponse_Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TrustVector   []byte                 `protobuf:"bytes,2,opt,name=trust_vector,json=trustVector,proto3" json:"trust_vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapResponse_Peer) Reset() {
	*x = GetMapResponse_Peer{}
	mi := &file_trust_anchor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapResponse_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapResponse_Peer) ProtoMessage() {}

func (x *GetMapResponse_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapResponse_Peer.ProtoReflect.Descriptor instead.
func (*GetMapResponse_Peer) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{15, 2}
}

func (x *GetMapResponse_Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMapResponse_Peer) GetTrustVector() []byte {
	if x != nil {
		return x.TrustVector
	}
	return nil
}

type GetCategoryResponse_KvPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse_KvPair) Reset() {
	*x = GetCategoryResponse_KvPair{}
	mi := &file_trust_anchor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse_KvPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse_KvPair) ProtoMessage() {}

func (x *GetCategoryResponse_KvPair) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse_KvPair.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse_KvPair) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetCategoryResponse_KvPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetCategoryResponse_KvPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type History_HistoryEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LeafIndex      int64                  `protobuf:"varint,1,opt,name=leaf_index,json=leafIndex,proto3" json:"leaf_index,omitempty"`
	DataHash       []byte                 `protobuf:"bytes,2,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	InclusionProof [][]byte               `protobuf:"bytes,3,rep,name=inclusion_proof,json=inclusionProof,proto3" json:"inclusion_proof,omitempty"`
	LogSize        int64                  `protobuf:"varint,4,opt,name=log_size,json=logSize,proto3" json:"log_size,omitempty"`
	LogRoot        []byte                 `protobuf:"bytes,5,opt,name=log_root,json=logRoot,proto3" json:"log_root,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *History_HistoryEntry) Reset() {
	*x = History_HistoryEntry{}
	mi := &file_trust_anchor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *History_HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History_HistoryEntry) ProtoMessage() {}

func (x *History_HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_trust_anchor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History_HistoryEntry.ProtoReflect.Descriptor instead.
func (*History_HistoryEntry) Descriptor() ([]byte, []int) {
	return file_trust_anchor_proto_rawDescGZIP(), []int{19, 0}
}

func (x *History_HistoryEntry) GetLeafIndex() int64 {
	if x != nil {
		return x.LeafIndex
	}
	return 0
}

func (x *History_HistoryEntry) GetDataHash() []byte {
	if x != nil {
		return x.DataHash
	}
	return nil
}

func (x *History_HistoryEntry) GetInclusionProof() [][]byte {
	if x != nil {
		return x.InclusionProof
	}
	return nil
}

func (x *History_HistoryEntry) GetLogSize() int64 {
	if x != nil {
		return x.LogSize
	}
	return 0
}

func (x *History_HistoryEntry) GetLogRoot() []byte {
	if x != nil {
		return x.LogRoot
	}
	return nil
}

var File_trust_anchor_proto protoreflect.FileDescriptor

const file_trust_anchor_proto_rawDesc = "" +
	"\n" +
	"\x12trust_anchor.proto\x12\ftrust_anchor\"\xbd\x04\n" +
	"\x12TrustAnchorRequest\x12+\n" +
	"\x05write\x18\x02 \x01(\v2\x13.trust_anchor.WriteH\x00R\x05write\x12(\n" +
	"\x04read\x18\x03 \x01(\v2\x12.trust_anchor.ReadH\x00R\x04read\x12H\n" +
	"\x10update_trust_vec\x18\x04 \x01(\v2\x1c.trust_anchor.UpdateTrustVecH\x00R\x0eupdateTrustVec\x125\n" +
	"\tadd_owner\x18\x05 \x01(\v2\x16.trust_anchor.AddOwnerH\x00R\baddOwner\x128\n" +
	"\n" +
	"set_config\x18\x06 \x01(\v2\x17.trust_anchor.SetConfigH\x00R\tsetConfig\x12/\n" +
	"\aget_map\x18\a \x01(\v2\x14.trust_anchor.GetMapH\x00R\x06getMap\x12>\n" +
	"\fget_category\x18\b \x01(\v2\x19.trust_anchor.GetCategoryH\x00R\vgetCategory\x12;\n" +
	"\vget_history\x18\t \x01(\v2\x18.trust_anchor.GetHistoryH\x00R\n" +
	"getHistory\x12?\n" +
	"\rget_other_ids\x18\n" +
	" \x01(\v2\x19.trust_anchor.GetOtherIdsH\x00R\vgetOtherIds\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderIdB\t\n" +
	"\arequest\"\x94\x05\n" +
	"\x13TrustAnchorResponse\x12<\n" +
	"\x0eempty_response\x18\x03 \x01(\v2\x13.trust_anchor.EmptyH\x00R\remptyResponse\x12A\n" +
	"\rread_response\x18\x04 \x01(\v2\x1a.trust_anchor.ReadResponseH\x00R\freadResponse\x12N\n" +
	"\x12add_owner_response\x18\x05 \x01(\v2\x1e.trust_anchor.AddOwnerResponseH\x00R\x10addOwnerResponse\x12H\n" +
	"\x10get_map_response\x18\x06 \x01(\v2\x1c.trust_anchor.GetMapResponseH\x00R\x0egetMapResponse\x12W\n" +
	"\x15get_category_response\x18\a \x01(\v2!.trust_anchor.GetCategoryResponseH\x00R\x13getCategoryResponse\x12I\n" +
	"\x14get_history_response\x18\b \x01(\v2\x15.trust_anchor.HistoryH\x00R\x12getHistoryResponse\x12X\n" +
	"\x16get_other_ids_response\x18\t \x01(\v2!.trust_anchor.GetOtherIdsResponseH\x00R\x13getOtherIdsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.trust_anchor.StatusR\x06status\x12*\n" +
	"\x11execution_time_us\x18\x02 \x01(\rR\x0fexecutionTimeUsB\n" +
	"\n" +
	"\bresponse\"\a\n" +
	"\x05Empty\"-\n" +
	"\x10AddOwnerResponse\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x04R\aownerId\"Q\n" +
	"\x05Write\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.trust_anchor.LocationR\blocation\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"_\n" +
	"\x04Read\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.trust_anchor.LocationR\blocation\x12#\n" +
	"\rinclude_proof\x18\x02 \x01(\bR\fincludeProof\"T\n" +
	"\fReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12.\n" +
	"\x05proof\x18\x02 \x01(\v2\x18.trust_anchor.ProofEntryR\x05proof\"\xa7\x01\n" +
	"\n" +
	"ProofEntry\x12\x1b\n" +
	"\tleaf_hash\x18\x01 \x01(\fR\bleafHash\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x02 \x01(\x03R\tleafIndex\x12\x19\n" +
	"\blog_root\x18\x03 \x01(\fR\alogRoot\x12\x19\n" +
	"\blog_size\x18\x04 \x01(\x03R\alogSize\x12'\n" +
	"\x0finclusion_proof\x18\x05 \x03(\fR\x0einclusionProof\"S\n" +
	"\bLocation\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x04R\aownerId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\fR\bcategory\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"R\n" +
	"\x0eUpdateTrustVec\x12\x1f\n" +
	"\void_trustee\x18\x01 \x01(\x04R\n" +
	"oidTrustee\x12\x1f\n" +
	"\vtrust_delta\x18\x02 \x03(\x05R\n" +
	"trustDelta\"\n" +
	"\n" +
	"\bAddOwner\"\x9e\x01\n" +
	"\tSetConfig\x12;\n" +
	"\aconfigs\x18\x01 \x03(\v2!.trust_anchor.SetConfig.CatConfigR\aconfigs\x1aT\n" +
	"\tCatConfig\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\fR\bcategory\x12+\n" +
	"\x11decision_function\x18\x02 \x01(\fR\x10decisionFunction\"=\n" +
	"\n" +
	"CortexData\x12\x1b\n" +
	"\tleaf_hash\x18\x01 \x01(\fR\bleafHash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x86\x01\n" +
	"\rAuditLogEntry\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.trust_anchor.LocationR\blocation\x12\x1b\n" +
	"\tdata_hash\x18\x02 \x01(\fR\bdataHash\x12$\n" +
	"\x0eprev_leaf_hash\x18\x03 \x01(\fR\fprevLeafHash\"\b\n" +
	"\x06GetMap\"\x93\x03\n" +
	"\x0eGetMapResponse\x12J\n" +
	"\x0eown_categories\x18\x01 \x03(\v2#.trust_anchor.GetMapResponse.OriginR\rownCategories\x127\n" +
	"\x05links\x18\x02 \x03(\v2!.trust_anchor.GetMapResponse.LinkR\x05links\x127\n" +
	"\x05peers\x18\x03 \x03(\v2!.trust_anchor.GetMapResponse.PeerR\x05peers\x1aE\n" +
	"\x06Origin\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\fR\n" +
	"categoryId\x12\x1a\n" +
	"\btrustees\x18\x02 \x03(\x04R\btrustees\x1aA\n" +
	"\x04Link\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x04R\aownerId\x12\x1e\n" +
	"\n" +
	"categories\x18\x02 \x01(\fR\n" +
	"categories\x1a9\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\ftrust_vector\x18\x02 \x01(\fR\vtrustVector\"D\n" +
	"\vGetCategory\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x04R\aownerId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\fR\bcategory\"\x8b\x01\n" +
	"\x13GetCategoryResponse\x12B\n" +
	"\aentries\x18\x01 \x03(\v2(.trust_anchor.GetCategoryResponse.KvPairR\aentries\x1a0\n" +
	"\x06KvPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"@\n" +
	"\n" +
	"GetHistory\x122\n" +
	"\blocation\x18\x01 \x01(\v2\x16.trust_anchor.LocationR\blocation\"\xf3\x01\n" +
	"\aHistory\x12<\n" +
	"\ahistory\x18\x01 \x03(\v2\".trust_anchor.History.HistoryEntryR\ahistory\x1a\xa9\x01\n" +
	"\fHistoryEntry\x12\x1d\n" +
	"\n" +
	"leaf_index\x18\x01 \x01(\x03R\tleafIndex\x12\x1b\n" +
	"\tdata_hash\x18\x02 \x01(\fR\bdataHash\x12'\n" +
	"\x0finclusion_proof\x18\x03 \x03(\fR\x0einclusionProof\x12\x19\n" +
	"\blog_size\x18\x04 \x01(\x03R\alogSize\x12\x19\n" +
	"\blog_root\x18\x05 \x01(\fR\alogRoot\"\r\n" +
	"\vGetOtherIds\"2\n" +
	"\x13GetOtherIdsResponse\x12\x1b\n" +
	"\tother_ids\x18\x01 \x03(\x04R\botherIds*3\n" +
	"\x06Status\x12\x06\n" +
	"\x02Ok\x10\x00\x12\x0e\n" +
	"\n" +
	"BadRequest\x10\x01\x12\x11\n" +
	"\rInternalError\x10\x022\xee\x04\n" +
	"\vTrustAnchor\x123\n" +
	"\x05write\x12\x13.trust_anchor.Write\x1a\x13.trust_anchor.Empty\"\x00\x128\n" +
	"\x04read\x12\x12.trust_anchor.Read\x1a\x1a.trust_anchor.ReadResponse\"\x00\x12E\n" +
	"\tadd_owner\x12\x16.trust_anchor.AddOwner\x1a\x1e.trust_anchor.AddOwnerResponse\"\x00\x12G\n" +
	"\x10update_trust_vec\x12\x1c.trust_anchor.UpdateTrustVec\x1a\x13.trust_anchor.Empty\"\x00\x12<\n" +
	"\n" +
	"set_config\x12\x17.trust_anchor.SetConfig\x1a\x13.trust_anchor.Empty\"\x00\x12?\n" +
	"\aget_map\x12\x14.trust_anchor.GetMap\x1a\x1c.trust_anchor.GetMapResponse\"\x00\x12N\n" +
	"\fget_category\x12\x19.trust_anchor.GetCategory\x1a!.trust_anchor.GetCategoryResponse\"\x00\x12@\n" +
	"\vget_history\x12\x18.trust_anchor.GetHistory\x1a\x15.trust_anchor.History\"\x00\x12O\n" +
	"\rget_other_ids\x12\x19.trust_anchor.GetOtherIds\x1a!.trust_anchor.GetOtherIdsResponse\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_trust_anchor_proto_rawDescOnce sync.Once
	file_trust_anchor_proto_rawDescData []byte
)

func file_trust_anchor_proto_rawDescGZIP() []byte {
	file_trust_anchor_proto_rawDescOnce.Do(func() {
		file_trust_anchor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trust_anchor_proto_rawDesc), len(file_trust_anchor_proto_rawDesc)))
	})
	return file_trust_anchor_proto_rawDescData
}

var file_trust_anchor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_trust_anchor_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_trust_anchor_proto_goTypes = []any{
	(Status)(0),                        // 0: trust_anchor.Status
	(*TrustAnchorRequest)(nil),         // 1: trust_anchor.TrustAnchorRequest
	(*TrustAnchorResponse)(nil),        // 2: trust_anchor.TrustAnchorResponse
	(*Empty)(nil),                      // 3: trust_anchor.Empty
	(*AddOwnerResponse)(nil),           // 4: trust_anchor.AddOwnerResponse
	(*Write)(nil),                      // 5: trust_anchor.Write
	(*Read)(nil),                       // 6: trust_anchor.Read
	(*ReadResponse)(nil),               // 7: trust_anchor.ReadResponse
	(*ProofEntry)(nil),                 // 8: trust_anchor.ProofEntry
	(*Location)(nil),                   // 9: trust_anchor.Location
	(*UpdateTrustVec)(nil),             // 10: trust_anchor.UpdateTrustVec
	(*AddOwner)(nil),                   // 11: trust_anchor.AddOwner
	(*SetConfig)(nil),                  // 12: trust_anchor.SetConfig
	(*CortexData)(nil),                 // 13: trust_anchor.CortexData
	(*AuditLogEntry)(nil),              // 14: trust_anchor.AuditLogEntry
	(*GetMap)(nil),                     // 15: trust_anchor.GetMap
	(*GetMapResponse)(nil),             // 16: trust_anchor.GetMapResponse
	(*GetCategory)(nil),                // 17: trust_anchor.GetCategory
	(*GetCategoryResponse)(nil),        // 18: trust_anchor.GetCategoryResponse
	(*GetHistory)(nil),                 // 19: trust_anchor.GetHistory
	(*History)(nil),                    // 20: trust_anchor.History
	(*GetOtherIds)(nil),                // 21: trust_anchor.GetOtherIds
	(*GetOtherIdsResponse)(nil),        // 22: trust_anchor.GetOtherIdsResponse
	(*SetConfig_CatConfig)(nil),        // 23: trust_anchor.SetConfig.CatConfig
	(*GetMapResponse_Origin)(nil),      // 24: trust_anchor.GetMapResponse.Origin
	(*GetMapResponse_Link)(nil),        // 25: trust_anchor.GetMapResponse.Link
	(*GetMapResponse_Peer)(nil),        // 26: trust_anchor.GetMapResponse.Peer
	(*GetCategoryResponse_KvPair)(nil), // 27: trust_anchor.GetCategoryResponse.KvPair
	(*History_HistoryEntry)(nil),       // 28: trust_anchor.History.HistoryEntry
}
var file_trust_anchor_proto_depIdxs = []int32{
	5,  // 0: trust_anchor.TrustAnchorRequest.write:type_name -> trust_anchor.Write
	6,  // 1: trust_anchor.TrustAnchorRequest.read:type_name -> trust_anchor.Read
	10, // 2: trust_anchor.TrustAnchorRequest.update_trust_vec:type_name -> trust_anchor.UpdateTrustVec
	11, // 3: trust_anchor.TrustAnchorRequest.add_owner:type_name -> trust_anchor.AddOwner
	12, // 4: trust_anchor.TrustAnchorRequest.set_config:type_name -> trust_anchor.SetConfig
	15, // 5: trust_anchor.TrustAnchorRequest.get_map:type_name -> trust_anchor.GetMap
	17, // 6: trust_anchor.TrustAnchorRequest.get_category:type_name -> trust_anchor.GetCategory
	19, // 7: trust_anchor.TrustAnchorRequest.get_history:type_name -> trust_anchor.GetHistory
	21, // 8: trust_anchor.TrustAnchorRequest.get_other_ids:type_name -> trust_anchor.GetOtherIds
	3,  // 9: trust_anchor.TrustAnchorResponse.empty_response:type_name -> trust_anchor.Empty
	7,  // 10: trust_anchor.TrustAnchorResponse.read_response:type_name -> trust_anchor.ReadResponse
	4,  // 11: trust_anchor.TrustAnchorResponse.add_owner_response:type_name -> trust_anchor.AddOwnerResponse
	16, // 12: trust_anchor.TrustAnchorResponse.get_map_response:type_name -> trust_anchor.GetMapResponse
	18, // 13: trust_anchor.TrustAnchorResponse.get_category_response:type_name -> trust_anchor.GetCategoryResponse
	20, // 14: trust_anchor.TrustAnchorResponse.get_history_response:type_name -> trust_anchor.History
	22, // 15: trust_anchor.TrustAnchorResponse.get_other_ids_response:type_name -> trust_anchor.GetOtherIdsResponse
	0,  // 16: trust_anchor.TrustAnchorResponse.status:type_name -> trust_anchor.Status
	9,  // 17: trust_anchor.Write.location:type_name -> trust_anchor.Location
	9,  // 18: trust_anchor.Read.location:type_name -> trust_anchor.Location
	8,  // 19: trust_anchor.ReadResponse.proof:type_name -> trust_anchor.ProofEntry
	23, // 20: trust_anchor.SetConfig.configs:type_name -> trust_anchor.SetConfig.CatConfig
	9,  // 21: trust_anchor.AuditLogEntry.location:type_name -> trust_anchor.Location
	24, // 22: trust_anchor.GetMapResponse.own_categories:type_name -> trust_anchor.GetMapResponse.Origin
	25, // 23: trust_anchor.GetMapResponse.links:type_name -> trust_anchor.GetMapResponse.Link
	26, // 24: trust_anchor.GetMapResponse.peers:type_name -> trust_anchor.GetMapResponse.Peer
	27, // 25: trust_anchor.GetCategoryResponse.entries:type_name -> trust_anchor.GetCategoryResponse.KvPair
	9,  // 26: trust_anchor.GetHistory.location:type_name -> trust_anchor.Location
	28, // 27: trust_anchor.History.history:type_name -> trust_anchor.History.HistoryEntry
	5,  // 28: trust_anchor.TrustAnchor.write:input_type -> trust_anchor.Write
	6,  // 29: trust_anchor.TrustAnchor.read:input_type -> trust_anchor.Read
	11, // 30: trust_anchor.TrustAnchor.add_owner:input_type -> trust_anchor.AddOwner
	10, // 31: trust_anchor.TrustAnchor.update_trust_vec:input_type -> trust_anchor.UpdateTrustVec
	12, // 32: trust_anchor.TrustAnchor.set_config:input_type -> trust_anchor.SetConfig
	15, // 33: trust_anchor.TrustAnchor.get_map:input_type -> trust_anchor.GetMap
	17, // 34: trust_anchor.TrustAnchor.get_category:input_type -> trust_anchor.GetCategory
	19, // 35: trust_anchor.TrustAnchor.get_history:input_type -> trust_anchor.GetHistory
	21, // 36: trust_anchor.TrustAnchor.get_other_ids:input_type -> trust_anchor.GetOtherIds
	3,  // 37: trust_anchor.TrustAnchor.write:output_type -> trust_anchor.Empty
	7,  // 38: trust_anchor.TrustAnchor.read:output_type -> trust_anchor.ReadResponse
	4,  // 39: trust_anchor.TrustAnchor.add_owner:output_type -> trust_anchor.AddOwnerResponse
	3,  // 40: trust_anchor.TrustAnchor.update_trust_vec:output_type -> trust_anchor.Empty
	3,  // 41: trust_anchor.TrustAnchor.set_config:output_type -> trust_anchor.Empty
	16, // 42: trust_anchor.TrustAnchor.get_map:output_type -> trust_anchor.GetMapResponse
	18, // 43: trust_anchor.TrustAnchor.get_category:output_type -> trust_anchor.GetCategoryResponse
	20, // 44: trust_anchor.TrustAnchor.get_history:output_type -> trust_anchor.History
	22, // 45: trust_anchor.TrustAnchor.get_other_ids:output_type -> trust_anchor.GetOtherIdsResponse
	37, // [37:46] is the sub-list for method output_type
	28, // [28:37] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_trust_anchor_proto_init() }
func file_trust_anchor_proto_init() {
	if File_trust_anchor_proto != nil {
		return
	}
	file_trust_anchor_proto_msgTypes[0].OneofWrappers = []any{
		(*TrustAnchorRequest_Write)(nil),
		(*TrustAnchorRequest_Read)(nil),
		(*TrustAnchorRequest_UpdateTrustVec)(nil),
		(*TrustAnchorRequest_AddOwner)(nil),
		(*TrustAnchorRequest_SetConfig)(nil),
		(*TrustAnchorRequest_GetMap)(nil),
		(*TrustAnchorRequest_GetCategory)(nil),
		(*TrustAnchorRequest_GetHistory)(nil),
		(*TrustAnchorRequest_GetOtherIds)(nil),
	}
	file_trust_anchor_proto_msgTypes[1].OneofWrappers = []any{
		(*TrustAnchorResponse_EmptyResponse)(nil),
		(*TrustAnchorResponse_ReadResponse)(nil),
		(*TrustAnchorResponse_AddOwnerResponse)(nil),
		(*TrustAnchorResponse_GetMapResponse)(nil),
		(*TrustAnchorResponse_GetCategoryResponse)(nil),
		(*TrustAnchorResponse_GetHistoryResponse)(nil),
		(*TrustAnchorResponse_GetOtherIdsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trust_anchor_proto_rawDesc), len(file_trust_anchor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trust_anchor_proto_goTypes,
		DependencyIndexes: file_trust_anchor_proto_depIdxs,
		EnumInfos:         file_trust_anchor_proto_enumTypes,
		MessageInfos:      file_trust_anchor_proto_msgTypes,
	}.Build()
	File_trust_anchor_proto = out.File
	file_trust_anchor_proto_goTypes = nil
	file_trust_anchor_proto_depIdxs = nil
}
